### ISSUE TITLE
local llm, with pdf rag feature 

### ISSUE THREAD

**Issue by sojudu** [shubham0204/Android-Document-QA#3]

**Comment by shubham0204** [comment]
See [this](https://github.com/shubham0204/Android-Document-QA/issues/7#issuecomment-2560543405) comment on how this feature will be managed.

**Comment by shubham0204** [comment]
See [this](https://github.com/shubham0204/Android-Document-QA/issues/7#issuecomment-2560543405) comment on how this feature will be managed.
